[package]
name = "lpmng-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.21.2"
pftables-rs = "0.1.1"
lpmng-mq = {path = "../lpmng-mq"}